alias scpresume="rsync --partial --progress --rsh=ssh"
alias ll="ls -l"
alias be="bundle exec"
alias gs="git status"
alias gd="git diff"
alias gp="git push"
alias gcm="git commit -m"
alias gco="git checkout"
alias gu="git-up"
